### ISSUE TITLE
How to exec into the container or pod

### ISSUE THREAD

**Issue by snail2sky** [kubewall/kubewall#47] opened 2024-10-10 07:26 UTC
Sometimes I need to log in to the container to debug my program, but it seems that it can't be done at the moment.

**Comment by snail2sky** [comment] 2024-10-10 07:26
Similar to using kubectl exec pod -c CONTAINER -- sh

**Comment by aslafy-z** [comment] 2024-10-10 07:51
This is a duplicate of #40

**Comment by abhimanyu003** [comment] 2024-10-10 13:36
Thanks so much for trying and feature suggestion. 
Also, thanks @aslafy-z for noticing it's duplicate. 

Sure we are working on SSH / Web-shell feature and will release an update soon.

I'm closing this in favor of #40

**Closed by abhimanyu003** 2024-10-10 13:36 UTC

**Comment by waldner** [comment] 2025-03-26 20:16
Any news on this one?
